// Code generated by protoc-gen-go.
// source: hello.proto
// DO NOT EDIT!

/*
Package com_zh_all is a generated protocol buffer package.

It is generated from these files:
	hello.proto

It has these top-level messages:
	Person
	ToBeGreeted
	Greeting
*/
package com_zh_all

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/wrappers"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Person struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ToBeGreeted struct {
	Person *Person                      `protobuf:"bytes,1,opt,name=person" json:"person,omitempty"`
	Msg    *google_protobuf.StringValue `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *ToBeGreeted) Reset()                    { *m = ToBeGreeted{} }
func (m *ToBeGreeted) String() string            { return proto.CompactTextString(m) }
func (*ToBeGreeted) ProtoMessage()               {}
func (*ToBeGreeted) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ToBeGreeted) GetPerson() *Person {
	if m != nil {
		return m.Person
	}
	return nil
}

func (m *ToBeGreeted) GetMsg() *google_protobuf.StringValue {
	if m != nil {
		return m.Msg
	}
	return nil
}

type Greeting struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *Greeting) Reset()                    { *m = Greeting{} }
func (m *Greeting) String() string            { return proto.CompactTextString(m) }
func (*Greeting) ProtoMessage()               {}
func (*Greeting) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Greeting) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Person)(nil), "com.zh.all.Person")
	proto.RegisterType((*ToBeGreeted)(nil), "com.zh.all.ToBeGreeted")
	proto.RegisterType((*Greeting)(nil), "com.zh.all.Greeting")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for HelloWorld service

type HelloWorldClient interface {
	SayHello(ctx context.Context, in *ToBeGreeted, opts ...grpc.CallOption) (*Greeting, error)
}

type helloWorldClient struct {
	cc *grpc.ClientConn
}

func NewHelloWorldClient(cc *grpc.ClientConn) HelloWorldClient {
	return &helloWorldClient{cc}
}

func (c *helloWorldClient) SayHello(ctx context.Context, in *ToBeGreeted, opts ...grpc.CallOption) (*Greeting, error) {
	out := new(Greeting)
	err := grpc.Invoke(ctx, "/com.zh.all.HelloWorld/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for HelloWorld service

type HelloWorldServer interface {
	SayHello(context.Context, *ToBeGreeted) (*Greeting, error)
}

func RegisterHelloWorldServer(s *grpc.Server, srv HelloWorldServer) {
	s.RegisterService(&_HelloWorld_serviceDesc, srv)
}

func _HelloWorld_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToBeGreeted)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloWorldServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.zh.all.HelloWorld/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloWorldServer).SayHello(ctx, req.(*ToBeGreeted))
	}
	return interceptor(ctx, in, info, handler)
}

var _HelloWorld_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.zh.all.HelloWorld",
	HandlerType: (*HelloWorldServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _HelloWorld_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}

func init() { proto.RegisterFile("hello.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xad, 0x4a, 0xac, 0x93, 0xdb, 0x20, 0x18, 0x4a, 0x11, 0x09, 0x1e, 0xc4, 0xc3, 0x14,
	0xea, 0xd1, 0x9b, 0x17, 0xf5, 0x26, 0xa9, 0xe8, 0x79, 0x6b, 0xc7, 0x6d, 0x60, 0xb3, 0xb3, 0xec,
	0xa6, 0x88, 0xfe, 0x7a, 0xe9, 0xc4, 0xa5, 0xb9, 0xed, 0xce, 0xfb, 0x98, 0xf7, 0x0d, 0x94, 0x5b,
	0x76, 0x4e, 0x28, 0x44, 0xe9, 0x05, 0xe1, 0x53, 0x3a, 0xfa, 0xdd, 0x92, 0x71, 0x6e, 0x76, 0x65,
	0x45, 0xac, 0xe3, 0x85, 0x26, 0xeb, 0xdd, 0xd7, 0xe2, 0x3b, 0x9a, 0x10, 0x38, 0xa6, 0x81, 0xad,
	0xe7, 0x50, 0xbc, 0x72, 0x4c, 0xe2, 0x11, 0xe1, 0xd4, 0x9b, 0x8e, 0xab, 0xc9, 0xf5, 0xe4, 0xf6,
	0xbc, 0xd1, 0x77, 0xdd, 0x42, 0xf9, 0x26, 0x8f, 0xfc, 0x14, 0x99, 0x7b, 0xde, 0xe0, 0x1d, 0x14,
	0x41, 0x61, 0x85, 0xca, 0x25, 0xd2, 0xa1, 0x89, 0x86, 0x35, 0xcd, 0x3f, 0x81, 0x04, 0x27, 0x5d,
	0xb2, 0xd5, 0xb1, 0x82, 0x73, 0x1a, 0x34, 0x28, 0x6b, 0xd0, 0xaa, 0x8f, 0xad, 0xb7, 0xef, 0xc6,
	0xed, 0xb8, 0xd9, 0x83, 0xf5, 0x0d, 0x4c, 0xb5, 0xa6, 0xf5, 0x16, 0x2b, 0x38, 0xeb, 0x38, 0x25,
	0x63, 0xb3, 0x4d, 0xfe, 0x2e, 0x5f, 0x00, 0x9e, 0xf7, 0x97, 0x7e, 0x48, 0x74, 0x1b, 0x7c, 0x80,
	0xe9, 0xca, 0xfc, 0xe8, 0x00, 0x2f, 0xc7, 0x2e, 0x23, 0xe9, 0xd9, 0xc5, 0x38, 0xc8, 0x15, 0xf5,
	0xd1, 0xba, 0x50, 0x97, 0xfb, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x79, 0x3d, 0xb1, 0x4e, 0x3b,
	0x01, 0x00, 0x00,
}
